---
- name: Parse and report vulnerabilities
  ansible.builtin.command: python3 /root/reporter.py {{ trivy_cache_path }}/*.trivy.json
  changed_when: false

- name: Cleanup trivy reports
  ansible.builtin.command: bash -c 'rm {{ trivy_cache_path }}/*.trivy.json'
  register: cleanup
  changed_when: cleanup.rc == 0
  ignore_errors: true
