---
- name: OCI Scanning
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: scan_docker
    - role: scan_podman
    - role: scan_containerd

- name: Report Vulnerabilities
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: report_vulnerabilities
